# FCopyRover Configuration File
# Поместите этот файл в директорию проекта для настройки поведения копирования

# ============================================================================
# ФИЛЬТРЫ ФАЙЛОВ
# ============================================================================

# Паттерны исключения (файлы/директории, которые НЕ будут копироваться)
exclude_patterns:
  - "*.tmp"           # Временные файлы
  - "*.log"           # Лог-файлы
  - "*.bak"           # Резервные копии
  - ".git/*"          # Git репозиторий
  - ".svn/*"          # SVN репозиторий
  - "node_modules/*"  # Node.js зависимости
  - "__pycache__/*"   # Python кэш
  - "*.pyc"           # Скомпилированные Python файлы
  - "build/*"         # Директории сборки
  - "dist/*"          # Директории дистрибутивов
  - ".DS_Store"       # macOS системные файлы
  - "Thumbs.db"       # Windows thumbnails

# Паттерны включения (если указаны, копируются ТОЛЬКО эти файлы)
# Оставьте пустым или используйте "*" для копирования всех файлов (кроме excluded)
include_patterns:
  - "*"

# ============================================================================
# НАСТРОЙКИ КОПИРОВАНИЯ
# ============================================================================

# Сохранять метаданные файлов (временные метки, права доступа)
preserve_metadata: true

# Следовать по символическим ссылкам
follow_symlinks: false

# Верифицировать целостность скопированных файлов (xxHash64)
verify: true

# ============================================================================
# ПРОИЗВОДИТЕЛЬНОСТЬ
# ============================================================================

# Количество рабочих потоков
# 0 или отсутствие значения = автоматический выбор (количество ядер CPU)
threads: 0

# Размер буфера I/O в байтах
# Рекомендуемые значения:
#   - 1048576 (1 MB) для SSD
#   - 4194304 (4 MB) для HDD
#   - 8388608 (8 MB) для сетевых дисков
buffer_size: 4194304

# ============================================================================
# ВОЗОБНОВЛЕНИЕ ОПЕРАЦИЙ
# ============================================================================

# Включить возобновление прерванных операций
# При включении создаётся файл .cclone.resume для отслеживания прогресса
resume: true

# ============================================================================
# ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ
# ============================================================================

# Пример 1: Копирование только исходного кода C++
# exclude_patterns: []
# include_patterns:
#   - "*.cpp"
#   - "*.hpp"
#   - "*.h"
#   - "CMakeLists.txt"

# Пример 2: Резервное копирование документов
# exclude_patterns:
#   - "~$*"           # Временные файлы Office
#   - "*.tmp"
# include_patterns:
#   - "*.docx"
#   - "*.xlsx"
#   - "*.pptx"
#   - "*.pdf"

# Пример 3: Высокопроизводительное копирование больших файлов
# threads: 16
# buffer_size: 8388608
# verify: true
# preserve_metadata: false  # Отключить для ускорения
