#include "args_parser.hpp"

#include <CLI/CLI.hpp>
#include <iostream>



namespace cclone::args_parser {

    std::optional<CLIArgs> parse_args(int argc, char const* const* argv)
    {
        CLI::App app{"FCopyRover ---- high-perfomance file copier tools"};


        CLIArgs args;

        // Sources: supporting both -s and positional arguments
        app.add_option(
            "-s, --sources",
            args.sources,
            "Source file(s) or directory (can be used multiple times)"
        ) -> required();

        // Destination: supporting both -d and last positional argument
        app.add_option(
            "-d, --destination",
            args.destination,
            "Destination file or directory"
        ) -> required();

        // Flags

        app.add_flag(
            "-r, --recursive",
            args.recursive,
            "Copy directories recursively"
        );

        app.add_flag(
            "--follow-symlinks",
            args.follow_symlinks,
            "Follow symbolic links"
        );

        app.add_flag(
            "--verify",
            args.verify,
            "Verify copied files"
        );

        app.add_flag(
            "--no-progress",
            args.progress,
            "Disable progress bar"
        )->transform(CLI::Transformer(std::map<std::string, bool>{{"", false}}));

        app.add_flag(
            "-q, --quiet",
            args.quiet,
            "Suppress non-error messages"
        );

        app.add_flag(
            "--resume",
            args.resume,
            "Resume interrupted copy operations"
        );

        app.add_flag(
            "--no-preserve-metadata",
            args.preserve_metadata,
            "Do not preserve file metadata (timestamps, permissions)"
        )->transform(CLI::Transformer(std::map<std::string, bool>{{"", false}}));

        // Parameters
        app.add_option(
            "--threads",
            args.threads,
            "Number of worker threads (default: auto)"
        );

        app.add_option(
            "--buffer-size",
            args.buffer_size,
            "I/O buffer size in bytes (e.g., 1048576 for 1MB)"
        );


        /// Help flag is auto-generated by CLI11
        try {
            app.parse(argc, argv);
        } catch (const CLI::CallForHelp&) {
            std::cout << app.help() << "\n";
            return std::nullopt; // Завершить
        } catch (const CLI::ParseError& e) {
            std::cerr << "Error: " << e.what() << "\n\n";
            std::cerr << app.help() << "\n";
            return std::nullopt; // Завершить с ошибкой
        }

        /// Postprocessing: invert progress flag
        args.progress = !args.progress;
        
        /// Postprocessing: invert preserve_metadata flag
        args.preserve_metadata = !args.preserve_metadata;

        return args;
    }

} // namespace cclone::args_parser